<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro">

    <xacro:property name="base_length" value="0.8" />
    <xacro:property name="base_width" value="0.5" />
    <xacro:property name="base_height" value="0.2" />
    <xacro:property name="wheel_radius" value="0.1" />
    <xacro:property name="wheel_length" value="0.05" />

    
    <link name="base_footprint" />

    <link name="base_link">
        <visual>
            <geometry>
                <box size="${base_length} ${base_width} ${base_height}" />
            </geometry>
            <origin xyz="0 0 ${base_height / 2.0}" rpy="0 0 0" />
            <material name="blue" />
        </visual>
    </link>

    <joint name="base_footprint_base_link_joint" type="fixed">
        <parent link="base_footprint" />
        <child link="base_link" />
        <origin xyz="0 0 ${wheel_radius}" rpy="0 0 0" />
    </joint>

    <xacro:macro name="wheel_link" params="prefix mesh_filename is_left">
        <link name="${prefix}_wheel_link">
            <visual>
                <geometry>
                    <mesh filename="package://mecannum_base_description/meshes/${mesh_filename}" scale="0.00133 0.00133 0.00092"/>
                </geometry>
                
                <!-- Define a temporary variable for adjusting the origin -->
                <xacro:property name="y_offset" value="0" />
                <xacro:if value="${is_left}">
                    <xacro:property name="y_offset" value="${-(base_width - wheel_length) / 2.0}" />
                </xacro:if>

                <origin xyz="0 ${y_offset} 0" rpy="${pi / 2} 0 0" />
                <material name="grey" />
            </visual>
        </link>
    </xacro:macro>



    
    <xacro:wheel_link prefix="rear_right" mesh_filename="Mecannum_Wheel_Left.stl" is_left="true" />

    <joint name="base_rear_right_wheel_joint" type="continuous">
        <parent link="base_link" />
        <child link="rear_right_wheel_link" />
        <origin xyz="${-base_length / 4.0} ${-(base_width + wheel_length) / 2.0} 0" rpy="0 0 0" />
        <axis xyz="0 1 0" />
    </joint>

    <xacro:wheel_link prefix="rear_left" mesh_filename="Mecannum_Wheel_Right.stl" is_left="false" />

    <joint name="base_rear_left_wheel_joint" type="continuous">
        <parent link="base_link" />
        <child link="rear_left_wheel_link" />
        <origin xyz="${-base_length / 4.0} ${(base_width + wheel_length) / 2.0} 0" rpy="0 0 0" />
        <axis xyz="0 1 0" />
    </joint>

    <xacro:wheel_link prefix="front_right" mesh_filename="Mecannum_Wheel_Right.stl" is_left="false" />

    <joint name="base_front_right_wheel_joint" type="continuous">
        <parent link="base_link" />
        <child link="front_right_wheel_link" />
        <origin xyz="${base_length / 4.0} ${-(base_width + wheel_length) / 2.0} 0" rpy="0 0 0" />
        <axis xyz="0 1 0" />
    </joint>

    <xacro:wheel_link prefix="front_left" mesh_filename="Mecannum_Wheel_Left.stl" is_left="true" />

    <joint name="base_front_left_wheel_joint" type="continuous">
        <parent link="base_link" />
        <child link="front_left_wheel_link" />
        <origin xyz="${base_length / 4.0} ${(base_width + wheel_length) / 2.0} 0" rpy="0 0 0" />
        <axis xyz="0 1 0" />
    </joint>

</robot>